Listen 8080
<VirtualHost *:8080>
    DocumentRoot "/var/www/html"
    ScriptAlias /cgi-bin/ "/var/www/cgi-bin/"
    <Directory "/var/www/cgi-bin">
        Options +ExecCGI
        AddHandler cgi-script .cgi .pl .py
        Require all granted
    </Directory>
    ErrorLog /var/log/httpd/error_log
    CustomLog /var/log/httpd/access_log combined
</VirtualHost>
# vim: syntax=apache ts=4 sw=4 sts=4 sr noet